updates:
  - directory: "/chrony"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/cron"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/dhcp-kea"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/dovecot"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/nsd"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/postfix"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/printer"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/restic"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/shell"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/syslog"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/tools"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
  - directory: "/unbound"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
version: 2
