version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/unbound'
    schedule:
      interval: 'daily'
