---
depends_on: []
kind: pipeline
name: build
steps:
- image: plugins/docker
  name: docker-zachfi/aur-build-image
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: aur-build-image
    daemon_off: true
    dockerfile: aur-build-image/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/aur-build-image
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/build-image
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: build-image
    daemon_off: true
    dockerfile: build-image/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/build-image
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/chrony
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: chrony
    daemon_off: true
    dockerfile: chrony/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/chrony
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/cron
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: cron
    daemon_off: true
    dockerfile: cron/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/cron
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/dhcp-kea
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: dhcp-kea
    daemon_off: true
    dockerfile: dhcp-kea/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/dhcp-kea
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/dovecot
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: dovecot
    daemon_off: true
    dockerfile: dovecot/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/dovecot
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/nsd
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: nsd
    daemon_off: true
    dockerfile: nsd/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/nsd
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/postfix
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: postfix
    daemon_off: true
    dockerfile: postfix/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/postfix
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/printer
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: printer
    daemon_off: true
    dockerfile: printer/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/printer
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/restic
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: restic
    daemon_off: true
    dockerfile: restic/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/restic
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/shell
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: shell
    daemon_off: true
    dockerfile: shell/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/shell
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/syslog
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: syslog
    daemon_off: true
    dockerfile: syslog/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/syslog
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/unbound
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: unbound
    daemon_off: true
    dockerfile: unbound/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: false
    repo: zachfi/unbound
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/heads/main
  - refs/tags/v*
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on: []
kind: pipeline
name: pr
steps:
- image: plugins/docker
  name: docker-zachfi/aur-build-image
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: aur-build-image
    daemon_off: true
    dockerfile: aur-build-image/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/aur-build-image
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/build-image
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: build-image
    daemon_off: true
    dockerfile: build-image/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/build-image
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/chrony
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: chrony
    daemon_off: true
    dockerfile: chrony/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/chrony
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/cron
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: cron
    daemon_off: true
    dockerfile: cron/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/cron
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/dhcp-kea
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: dhcp-kea
    daemon_off: true
    dockerfile: dhcp-kea/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/dhcp-kea
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/dovecot
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: dovecot
    daemon_off: true
    dockerfile: dovecot/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/dovecot
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/nsd
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: nsd
    daemon_off: true
    dockerfile: nsd/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/nsd
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/postfix
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: postfix
    daemon_off: true
    dockerfile: postfix/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/postfix
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/printer
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: printer
    daemon_off: true
    dockerfile: printer/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/printer
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/restic
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: restic
    daemon_off: true
    dockerfile: restic/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/restic
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/shell
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: shell
    daemon_off: true
    dockerfile: shell/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/shell
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/syslog
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: syslog
    daemon_off: true
    dockerfile: syslog/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/syslog
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- image: plugins/docker
  name: docker-zachfi/unbound
  platform: linux/amd64,linux/arm64
  pull_image: true
  settings:
    compress: true
    context: unbound
    daemon_off: true
    dockerfile: unbound/Dockerfile
    dry_run: true
    ipv6: true
    password:
      from_secret: DOCKER_PASSWORD
    purge: true
    repo: zachfi/unbound
    username:
      from_secret: DOCKER_USERNAME
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  branch:
    exclude:
    - main
  event:
  - push
  - pull_request
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on:
- build
kind: pipeline
name: localpush
steps:
- commands:
  - docker tag zachfi/aur-build-image:latest reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image:latest
  image: zachfi/build-image
  name: aur-build-image
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/build-image:latest reg.dist.svc.cluster.znet:5000/zachfi/build-image:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/build-image:latest
  image: zachfi/build-image
  name: build-image
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/chrony:latest reg.dist.svc.cluster.znet:5000/zachfi/chrony:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/chrony:latest
  image: zachfi/build-image
  name: chrony
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/cron:latest reg.dist.svc.cluster.znet:5000/zachfi/cron:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/cron:latest
  image: zachfi/build-image
  name: cron
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/dhcp-kea:latest reg.dist.svc.cluster.znet:5000/zachfi/dhcp-kea:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/dhcp-kea:latest
  image: zachfi/build-image
  name: dhcp-kea
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/dovecot:latest reg.dist.svc.cluster.znet:5000/zachfi/dovecot:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/dovecot:latest
  image: zachfi/build-image
  name: dovecot
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/nsd:latest reg.dist.svc.cluster.znet:5000/zachfi/nsd:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/nsd:latest
  image: zachfi/build-image
  name: nsd
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/postfix:latest reg.dist.svc.cluster.znet:5000/zachfi/postfix:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/postfix:latest
  image: zachfi/build-image
  name: postfix
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/printer:latest reg.dist.svc.cluster.znet:5000/zachfi/printer:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/printer:latest
  image: zachfi/build-image
  name: printer
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/restic:latest reg.dist.svc.cluster.znet:5000/zachfi/restic:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/restic:latest
  image: zachfi/build-image
  name: restic
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/shell:latest reg.dist.svc.cluster.znet:5000/zachfi/shell:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/shell:latest
  image: zachfi/build-image
  name: shell
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/syslog:latest reg.dist.svc.cluster.znet:5000/zachfi/syslog:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/syslog:latest
  image: zachfi/build-image
  name: syslog
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- commands:
  - docker tag zachfi/unbound:latest reg.dist.svc.cluster.znet:5000/zachfi/unbound:latest
  - docker push reg.dist.svc.cluster.znet:5000/zachfi/unbound:latest
  image: zachfi/build-image
  name: unbound
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  branch:
  - main
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on:
- localpush
kind: pipeline
name: cleanup
steps:
- commands:
  - docker system prune -f
  image: zachfi/build-image
  name: cleanup
  pull: always
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  branch:
  - main
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: 25b2df3201dbe470c8e2132c2dc516d4827bbec57f393dc9ed9fc763ac79f3c1

...
