"services":
- "environment":
    "DOCKER_TLS_CERTDIR": ""
  "image": "docker:24-dind"
  "name": "docker"
  "privileged": true
"skip_clone": true
"steps":
- "image": "woodpeckerci/plugin-git"
  "name": "clone"
  "pull": true
- "commands":
  - "make build-dovecot"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
    "DOCKER_TLS_VERIFY": "0"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/shell:latest"
  "name": "build"
  "pull": true
- "commands":
  - "make push-dovecot"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
    "DOCKER_TLS_VERIFY": "0"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/shell:latest"
  "name": "push"
  "pull": true
  "when":
    "branch": "main"
    "event": "push"
"when":
  "event":
  - "push"
  - "pull_request"
  "path": "dovecot/**"