"skip_clone": true
"steps":
- "image": "woodpeckerci/plugin-git"
  "name": "clone"
  "pull": true
- "commands":
  - "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
    "DOCKER_HUB_TOKEN":
      "from_secret": "docker_hub_token"
    "DOCKER_HUB_USER":
      "from_secret": "docker_hub_user"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/shell:latest"
  "name": "docker-login"
  "pull": true
- "commands":
  - "make build-unbound"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/shell:latest"
  "name": "build"
  "pull": true
- "commands":
  - "make push-unbound"
  "environment":
    "DOCKER_HOST": "tcp://docker:2375"
  "image": "reg.dist.svc.cluster.znet:5000/zachfi/shell:latest"
  "name": "push"
  "pull": true
  "when":
    "branch": "main"
    "event": "push"
"when":
  "event":
  - "push"
  - "pull_request"
  - "manual"
  "path": "unbound/**"